### ISSUE TITLE
build component markup in components folder (npm build)

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#104]
To better support integrating our components into cms systems or other projects we should provide markup for a component without handlebars template tags and includes.

todo:
- on gulp build add the markup of each component to the components folder
- html beautify: **https://github.com/c0b41/gulp-htmltidy**
- dev notes (backend integration comments) should stay in the markup! (this is maybe complicated since we are using hbs comments, but a must in my oppinion)

**Comment by janrembold** [comment]
See https://github.com/biotope/biotope-build/issues/80 for depending naming conventions for HBS entry points

**Comment by janrembold** [comment]
@timomayer We need another naming convention to mark the files that should be statically rendered. We can't render all files because they need some entry points that include template data. The "normal" HBS templates don't have data included. 

We could do something like `demo.*.hbs` or `static.*.hbs` that are used for rendering. What do you think?

**Comment by timomayer** [comment]
can we not just use the index.*.hbs i dont prever another hbs file. Can we not just inject our demo data into the hbs task?

**Comment by jurekbarth** [comment]
@timomayer is this still relevant? I'll close and if necessary please reopen 👍
