### ISSUE TITLE
source map files are included into build by default but not referenced correctly

### ISSUE THREAD

**Issue by clemensf** [biotope/biotope-build#116]
Since version 5.3.x source map files are also copied into the /dist directory by default.

However source map files are referenced relatively but cannot be found on the server when requested by s browser, which is requesting files absolutely in the web root. This results in 404 errors for nearly all source map files.

Also enabling source map files could be conflicting with customer contracts where source code should not be published in human readable format.

Therefore:
1. source maps should be disabled (for production build) by default
2. references to source map files need to be fixed

**Comment by janrembold** [comment]
The bug is easy to identify but (might be) not so easy to fix :( This needs further investigations.

1. Webpack transpiles TS scripts and creates a valid sourcemap for each file 
2. Useref concatenates all files into a single file
3. Uglify minifies this concatenated file again and creates an invalid sourcemap for that because it doesn't respect the existing sourcemaps

**Comment by jurekbarth** [comment]
@janrembold It's not fixable with our current setup of webpack and gulp-uglify. 

@clemensf  you could disable sourcemaps here: https://github.com/biotope/biotope-build/blob/master/config.js#L179 

For now i'll close this issue. We'll keep that in mind with the changes for our new build system. Feel free to reopen if you find a fix or you really need support for production sourcemaps.
