### ISSUE TITLE
Serve process log output URL wrong (0.0.0.0:9000)

### ISSUE THREAD

**Issue by luke-m** [biotope/biotope-build#184]
![image](https://user-images.githubusercontent.com/16318844/53631265-70240f00-3c12-11e9-853b-6e96a94e5335.png)

The serve process still actually opens the browser to the right URL (localhost:9000) when it's finished initializing but the console output is wrong.

Windows 10,
Biotope 6.0.0

**Comment by jurekbarth** [comment]
It’s maybe not nice but Windows cannot resolve 0.0.0.0. We are defaulting to 0.0.0.0 because otherwise local network requests won’t be resolved correctly. Still we wanted to open a new browser tab with a url that works everywhere, thats why it’s not opening 0.0.0.0:9000 :) 

We could change the output to localhost:9000 but that would be even more confusing because in the config.js 0.0.0.0 is the host. 

If anyone has a nicer way to go forward i would appreciate input :) 

@like-m I really enjoyed this issue, still i don’t know how to enhance this specific topic. Does this make any sense for you?

**Comment by luke-m** [comment]
Could you detect the OS and then set the output to localhost:9000 for windows?

![image](https://user-images.githubusercontent.com/16318844/53795168-ac68af80-3f31-11e9-9f4e-e59070f0ca57.png)
This works because of this:
![image](https://user-images.githubusercontent.com/16318844/53795194-b8547180-3f31-11e9-8a96-a45e02e77d28.png)

**Comment by jurekbarth** [comment]
@luke-m sure would you like to submit a pr?

**Comment by jurekbarth** [comment]
@luke-m i rethought about it and changing that in that way makes no sense because then windows would also not serve that stuff over the network from a different address. Changing the output of connect might be an option. Please reopen if necessary or submit a pr 👍
