### ISSUE TITLE
uppercase .json adressing in scaffolding

### ISSUE THREAD

**Issue by simonbraunbrown** [biotope/biotope-build#195]
If someone names a .json file beginning with a uppercase letter (for what reason ever) and adress with the same naming it in the scaffolding, no object could be found and now error is thrown. If you then rename with lowercase only in the scafffolding and leave the .joson naming uppercase, it then will work  

1. you create a **A**ccordionObj.json
2. reference it in the scaffolding with accordion = data.components.accordion.**A**ccordionOb
3. no object is found, no error

**Expected behavior**
if the naming is identical, referencing should work no matter objects are named lowercase  conventionally.

**Comment by SheepFromHeaven** [comment]
We no longer will have handelbars in a future version, so I would not want to investigate this task any further.
Until the new version gets publicly released, please just stick to the lowercase convention.

**Comment by timomayer** [comment]
I disagree, we have and we ll have a lot of projects which use handlebars for a long time since there is no migration path to none handlebars version, so i think this argument is not valid for closing this ticket

**Comment by jurekbarth** [comment]
Thats because we camel case the path so `src/components/XButton/scaffolding/XButtonData.json` would later be available in the hbs scope via `data.components.xButton.scaffolding.xButtonData`. I think it's a matter of documentation. 
We use that aswell for normalizing filenames with spaces, so i think we should not change that 👍 Adding a warning is maybe a little bit annoying, so i will leave it as is.
For debugging the hbs scope you could print the whole scope with:
```
{{bioStringify data}}

// for the button data itself
{{bioStringify data.components.xButton}}
```
