### ISSUE TITLE
add svg sprite support

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#46]
https://github.com/shakyShane/gulp-svg-sprites

**Comment by luiswill** [comment]
I tested that module and it's working fine and could be included in the framework.

Code snippet in `iconfont.js` gulp task : 

```
gulp.task('convertIconsToSprites', function () {
	const svgSprite = require('gulp-svg-sprites');

	return gulp.src(config.global.src + config.global.resources + '/icons/*.svg')
		.pipe(svgSprite({
			baseSize: 1
		}))
		.pipe(gulp.dest(config.global.dev + config.global.resources + '/sprite'));
});

```
### Settings changed
- Basesize changed to 1px (default : 10px https://github.com/shakyShane/gulp-svg-sprites#options)
 (to have more power when using percentage font-size)


### How to use icons ? 
```
.testContainer {
	.icon:before {
		font-size: 2%;
		// font-size: 3px;
	}
}
```
You need to change the font-size value of that icon. Changing the container in height or width is not possible because all icons are assembled in `sprite.svg` on which sprite.svg will access through background-position

### What we could change

- The preview `sprite.html ` is stored in `.tmp/resources/sprite/`. 
- `sprite.css` file is imported in the `htmlhead.styles.hbs` as an extra file. It would be great to import it directly in `styles.css`. The problem is that `sprite.css` is already CSS. 


I would really appreciate your suggestions and comments.

**Comment by janrembold** [comment]
@luiswill Was that tested in all, especially older browsers? At least IE11 is necessary in my opinion.

It would also be good to integrate that task in its own file and not combining it with the existing iconfont task.

**Comment by timomayer** [comment]
@luiswill ??

**Comment by timomayer** [comment]
@jonerd  are you working on that?
